// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiaS26GPZKC9AX1bzGjm8bXEb8yWUQmjw',
    appId: '1:135607758145:web:fe7fcdcdc35323920785c0',
    messagingSenderId: '135607758145',
    projectId: 'pet-adoption-88a6b',
    authDomain: 'pet-adoption-88a6b.firebaseapp.com',
    storageBucket: 'pet-adoption-88a6b.firebasestorage.app',
    measurementId: 'G-DWDZKDE6DV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDttHD1ohFr4gQYk5_NJLX5eRnVy2nMQCs',
    appId: '1:135607758145:android:5134b03192eda6640785c0',
    messagingSenderId: '135607758145',
    projectId: 'pet-adoption-88a6b',
    storageBucket: 'pet-adoption-88a6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9qs_kEcmHToyEsFZtNjhZKi3ZCAVc9-M',
    appId: '1:135607758145:ios:216e5bf22cd5577e0785c0',
    messagingSenderId: '135607758145',
    projectId: 'pet-adoption-88a6b',
    storageBucket: 'pet-adoption-88a6b.firebasestorage.app',
    iosBundleId: 'com.example.petAdoption',
  );
}
